no type hints on create if implements SecurityFactoryInterface in sec…
oat-sa/bundle-lti1p3 pull request #5
Opened 2020-04-14 14:51 UTC by m-lagarde

The purpose of this PR is to make the bundle work in a sf 4.2 context

2020-04-14 17:08 UTC, emgolubev approved these changes

2020-04-22 08:34 UTC, ekkinox requested changes

2020-04-22 08:34 UTC, ekkinox commented on DependencyInjection/Security/Factory/LtiLaunchRequestSecurityFactory.php
> +        $id,
can I ask you to add a TODO as a comment to revert this, the day we will move all our apps to SF > 4.2 ?

2020-04-22 08:41 UTC, ekkinox approved these changes

2020-04-22 08:42 UTC, merged