Bump versions & remove unsupported versions
oat-sa/bundle-lti1p3 pull request #60
Opened 2023-10-05 21:53 UTC by kochen

2023-12-01 06:19 UTC, ekkinox approved these changes

2023-12-04 13:07 UTC, kochen commented
@wazelin could you please take a look at this as well?

2023-12-04 13:21 UTC, wazelin requested changes

2023-12-04 13:21 UTC, wazelin commented on composer.json
> +        "psr/log": "^2 || ^3",
While it does make sense to drop support for `psr/log`, now that PHP 7 support is getting dropped, and this is a breaking change anyway, I still would like to leave version 1 as an option here.
I will help in organizing migration in other repositories of ours.

Thanks!
```suggestion
        "psr/log": "^1 || ^2 || ^3",
```

2023-12-04 20:57 UTC, wazelin approved these changes

2023-12-04 20:59 UTC, merged

2023-12-04 21:03 UTC, wazelin commented
Released as part of https://github.com/oat-sa/bundle-lti1p3/releases/tag/7.0.0

Once again, thanks very much for this contribution! Much appreciated.